### ISSUE TITLE
Detecting the destination language of the browser's built-in translation

### ISSUE THREAD

**Issue by hata6502** [webmachinelearning/translation-api#22]
Currently, There is no standard specification to detect the translation destination language by browser's built-in translation
Enabling the browser's built-in translation function does not fire the [languagechange](https://developer.mozilla.org/en-US/docs/Web/API/Window/languagechange_event) event or change [navigator.language](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language) property.
[![Image from Gyazo](https://i.gyazo.com/a6b9ade30568cebe33badfaa22a37b11.png)](https://gyazo.com/a6b9ade30568cebe33badfaa22a37b11)

There is no other way but to use the npm package, which detects the destination language in a browser-hack-like way
However the behavior may not be stable.
- https://github.com/ClaudiuCeia/detect-translation?tab=readme-ov-file#use-a-skip-to-main-contentlink-for-more-reliable-matches
- Provide your own translated text with the browser's built-in translation UI
  - https://github.com/hata6502/react-controlled-translation demo

Does the Language Detector API include specifications for detecting the destination language of the browser's built-in translation?

**Comment by hata6502** [comment]
I feel that it is easier to notice the browser's built-in translation feature than implementing a language selection UI for each website.
[![Image from Gyazo](https://i.gyazo.com/a6b9ade30568cebe33badfaa22a37b11.png)](https://gyazo.com/a6b9ade30568cebe33badfaa22a37b11)
[![Image from Gyazo](https://t.gyazo.com/teams/nota/861f4457e646c61455b72204b7fe88ec.png)](https://nota.gyazo.com/861f4457e646c61455b72204b7fe88ec)

**Comment by aphillips** [comment]
> I feel that it may be easier to notice the browser's built-in translation feature than implementing a language selection UI for each website.

That may be true, but there are reasons why websites need to control which languages and (as important!) locales they provide. Content or relevant user experience cannot always be served by every site. The translation feature's settings might provide a useful hint during language negotiation (I happen to be working on a [tutorial](https://github.com/aphillips/i18n-drafts/blob/gh-pages/articles/language-negotiation/language-negotiation.md) about this at the moment).

**Comment by hata6502** [comment]
Thank you for suggesting the Language Negotiation!

**Comment by hata6502** [comment]
Thank you for suggesting the Language Negotiation!

https://github.com/aphillips/i18n-drafts/blob/gh-pages/articles/language-negotiation/language-negotiation.md#what-if-the-user-doesnt-like-the-results
I think both browser built-in UI and each website UI are UI to choose the language for herself.

**Comment by domenic** [comment]
Thanks for your interest!

This idea is outside the scope of the proposal we are working on here. What we are working on here is a JavaScript API to allow web developers to perform translation (and language detection). It has no interaction with the browser's built-in translation.

You are welcome to propose such an idea at https://github.com/WICG/proposals. If you do, please leave a link here so interested folks can follow. But, since it is not related to the API we are developing here, I will close this issue.
